export const MOVEMENT_TRAIL_PANE = "movementTrailPane"

export const MOVEMENT_TRAIL_MAX_BACKGROUND_RAW_POINTS = 140
export const MOVEMENT_TRAIL_MAX_SELECTED_RAW_POINTS = 900
export const MOVEMENT_TRAIL_MAX_RENDER_POINTS = 55
export const MOVEMENT_TRAIL_MAX_VIEWPORT_ENTRIES = 350

export const MOVEMENT_TRAIL_MIN_RENDER_ZOOM = 13
export const MOVEMENT_TRAIL_MIN_START_MARKER_ZOOM = 15
export const MOVEMENT_TRAIL_MAX_START_MARKERS = 80
export const MOVEMENT_TRAIL_MIN_DISTANCE_METERS = 14
export const MOVEMENT_TRAIL_MAX_JUMP_METERS = 5000
export const MOVEMENT_TRAIL_VIEWPORT_PADDING = 0.18

export const RENDER_MOVEMENT_TRAILS_MEASURE = "renderMovementTrails"
