export const HEAVY_ITINERARY_ROWS_THRESHOLD = 5000

export const itineraryTablePageSizeOptions = [25, 50, 100, 200]

export const itineraryStatusOrder = {
  moving: 1,
  stopped: 2,
  idle: 3,
  offline: 4,
}

export const itineraryStatusLabels = {
  moving: "Movimiento",
  stopped: "Detenido",
  idle: "Espera",
  offline: "Offline",
}

export const itineraryTableColumns = [
  {
    key: "timestamp",
    label: "Hora",
    width: "104px",
    locked: true,
  },
  {
    key: "status",
    label: "Estado",
    width: "118px",
  },
  {
    key: "ignition",
    label: "Encendido",
    width: "104px",
    telemetry: true,
  },
  {
    key: "speed",
    label: "Vel.",
    width: "92px",
    align: "right",
  },
  {
    key: "address",
    label: "Direccion",
    width: "260px",
  },
  {
    key: "accumulatedDistanceKm",
    label: "Km acum.",
    width: "110px",
    align: "right",
  },
  {
    key: "combustible",
    label: "Comb.",
    width: "86px",
    align: "right",
    telemetry: true,
    numeric: true,
  },
  {
    key: "gpsSatellites",
    label: "Satelites",
    width: "90px",
    align: "right",
    telemetry: true,
    numeric: true,
  },
  {
    key: "canRpm",
    label: "RPM",
    width: "90px",
    align: "right",
    telemetry: true,
    numeric: true,
  },
  {
    key: "canEngineTemp",
    label: "Temp. motor",
    width: "105px",
    align: "right",
    telemetry: true,
    numeric: true,
  },
  {
    key: "canBatteryVoltage",
    label: "Voltaje",
    width: "90px",
    align: "right",
    telemetry: true,
    numeric: true,
  },
  {
    key: "canEngineLoad",
    label: "Carga motor",
    width: "105px",
    align: "right",
    telemetry: true,
    numeric: true,
  },
  {
    key: "gpsSignal",
    label: "Senal GPS",
    width: "95px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "odometro",
    label: "Odometro",
    width: "112px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "horometroTotal",
    label: "Horometro",
    width: "105px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "horometroDiario",
    label: "Hor. diario",
    width: "100px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "canThrottle",
    label: "Acelerador",
    width: "105px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "canFuelRate",
    label: "Cons. L/h",
    width: "95px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "canFuelUsed",
    label: "Comb. usado",
    width: "112px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "canOilPressure",
    label: "Pres. aceite",
    width: "108px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "canAdBlueLevel",
    label: "AdBlue",
    width: "88px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "canDtcCount",
    label: "DTC",
    width: "76px",
    align: "right",
    defaultVisible: false,
    telemetry: true,
    numeric: true,
  },
  {
    key: "digitalInput1",
    label: "Entrada 1",
    width: "96px",
    defaultVisible: false,
    telemetry: true,
  },
  {
    key: "digitalInput2",
    label: "Entrada 2",
    width: "96px",
    defaultVisible: false,
    telemetry: true,
  },
  {
    key: "assetDisplayName",
    label: "Activo",
    width: "150px",
    defaultVisible: false,
  },
  {
    key: "assetPatente",
    label: "Patente",
    width: "115px",
    defaultVisible: false,
  },
  {
    key: "assetDeviceId",
    label: "Dispositivo",
    width: "130px",
    defaultVisible: false,
  },
  {
    key: "dateLabel",
    label: "Fecha",
    width: "115px",
    defaultVisible: false,
  },
  {
    key: "event",
    label: "Evento",
    width: "150px",
    defaultVisible: false,
  },
  {
    key: "lat",
    label: "Latitud",
    width: "110px",
    align: "right",
    defaultVisible: false,
  },
  {
    key: "lng",
    label: "Longitud",
    width: "110px",
    align: "right",
    defaultVisible: false,
  },
]

export const normalizeItineraryTableText = (value) => {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ")
}
